server:
  port: 8089
  servlet:
    context-path: /
spring:
  datasource:
    druid:
      url:  jdbc:mysql://localhost:3306/demo2?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      username: root
      password: root
      max-active: 20
      max-wait: 5000
      initial-size: 1
      filters: stat,log4j,wall
      validationQuery: SELECT 'x'   #验证连接
      enable: true
      #监控配置
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123456
        allow:
        deny:
        url-pattern: /druid/*
  main:
    allow-bean-definition-overriding: true
#mybatis:
#  type-aliases-package: com.wzw.microboot.entity
#  mapper-locations: classpath*:mapper/*.xml
#  check-config-location: true
  #thymeleaf的配置
  thymeleaf:
    cache: false
    enabled: true
  #      web-stat-filter:
  #        enabled: true
  #        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  mapper-locations:
    classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
    banner: true

shiro:
  hash-algorithm-name: md5
  hash-iterations: 2
  anon-urls:
    - /index.html*
    - /login.html*
    - /sys/toLogin*
    - /login/login*
    - /resources/**
  login-url: /index.html
  log-out-url: /login/logout*
  authc-ulrs:
  - /**